[build-system]
requires = ["maturin>=1.12.2,<1.13"]
build-backend = "maturin"

[project]
name = "strkit_rust_ext"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
dynamic = ["version"]
